name: Build MAUI Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

       # Install Android SDK
      - name: Install Android SDK
        uses: github-actions/setup-android-sdk@v2
        with:
          sdk-version: '35'

      # Set up .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Specify your MAUI-compatible .NET version

      # Install dependencies
      - name: Install dependencies
        run: dotnet workload install maui-android

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore

      # Build the MAUI Android project
      - name: Build MAUI Android
        run: dotnet build -t:Build -f:net9.0-android --configuration Release
